[project]
name = 'nftmarketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.marketplace]
path = 'contracts/marketplace.clar'
clarity_version = 3
epoch = 'latest'

[contracts.marketplacels]
path = 'contracts/marketplacels.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
